"""baseline schema

Revision ID: 274ec27623aa
Revises: 
Create Date: 2026-06-14 03:36:37.156749+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274ec27623aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'ESCALATED', name='workflow_status', native_enum=False), nullable=False),
    sa.Column('dag_definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('human_input', sa.Text(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('llm_tokens_accumulated', sa.Integer(), nullable=False),
    sa.Column('parent_workflow_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_parent_workflow_id'), 'workflows', ['parent_workflow_id'], unique=False)
    op.create_table('task_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='task_node_status', native_enum=False), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('previous_node_ids', sa.JSON(), nullable=False),
    sa.Column('next_node_ids', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('compensation_command', sa.Text(), nullable=True),
    sa.Column('compensation_arguments', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_nodes_workflow_id'), 'task_nodes', ['workflow_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_node_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('NODE_STARTED', 'NODE_COMPLETED', 'NODE_FAILED', 'COMPENSATION_TRIGGERED', 'COMPENSATION_COMPLETED', 'COMPENSATION_FAILED', 'STATE_CHECKPOINT', 'WORKFLOW_SUBMITTED', 'WORKFLOW_COMPLETED', 'WORKFLOW_FAILED', 'OBSERVATION_CAPTURED', 'PLAN_GENERATED', 'EVALUATION_RESULT', 'PRECONDITION_CHECKED', 'CYCLE_STARTED', 'CHECKPOINT', 'ESCALATE', 'WORKFLOW_PAUSED', 'HUMAN_INPUT_RECEIVED', 'WORKFLOW_RESUMED', 'SECURITY_AUDIT', 'WORKSPACE_SPAWN', 'WORKSPACE_DESTROY', name='task_event_type', native_enum=False), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_node_id'], ['task_nodes.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_events_correlation', 'task_events', ['correlation_id'], unique=False)
    op.create_index('idx_task_events_wf_type', 'task_events', ['workflow_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_task_node_id'), 'task_events', ['task_node_id'], unique=False)
    op.create_index(op.f('ix_task_events_workflow_id'), 'task_events', ['workflow_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('task_node_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('NODE_STARTED', 'NODE_COMPLETED', 'NODE_FAILED', 'COMPENSATION_TRIGGERED', 'COMPENSATION_COMPLETED', 'COMPENSATION_FAILED', 'STATE_CHECKPOINT', 'WORKFLOW_SUBMITTED', 'WORKFLOW_COMPLETED', 'WORKFLOW_FAILED', 'OBSERVATION_CAPTURED', 'PLAN_GENERATED', 'EVALUATION_RESULT', 'PRECONDITION_CHECKED', 'CYCLE_STARTED', 'CHECKPOINT', 'ESCALATE', 'WORKFLOW_PAUSED', 'HUMAN_INPUT_RECEIVED', 'WORKFLOW_RESUMED', 'SECURITY_AUDIT', 'WORKSPACE_SPAWN', 'WORKSPACE_DESTROY', name='task_event_type', native_enum=False), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_node_id'], ['task_nodes.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'sequence_number', name='uq_workflow_events_wf_seq')
    )
    op.create_index('idx_workflow_events_correlation', 'workflow_events', ['correlation_id'], unique=False)
    op.create_index('idx_workflow_events_wf_type', 'workflow_events', ['workflow_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_event_type'), 'workflow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_task_node_id'), 'workflow_events', ['task_node_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_workflow_id'), 'workflow_events', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_workflow_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_task_node_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_event_type'), table_name='workflow_events')
    op.drop_index('idx_workflow_events_wf_type', table_name='workflow_events')
    op.drop_index('idx_workflow_events_correlation', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_task_events_workflow_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_node_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_index('idx_task_events_wf_type', table_name='task_events')
    op.drop_index('idx_task_events_correlation', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_task_nodes_workflow_id'), table_name='task_nodes')
    op.drop_table('task_nodes')
    op.drop_index(op.f('ix_workflows_parent_workflow_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
